# Generated by Django 6.0.3 on 2026-04-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
