# Generated by Django 6.0.3 on 2026-04-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_videojob_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojob',
            name='progress',
        ),
        migrations.AddField(
            model_name='videojob',
            name='status_message',
            field=models.TextField(default='Starting...'),
        ),
    ]
