# Generated by Django 6.0.3 on 2026-04-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_videojob_progress_videojob_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
